version: '3.8'

services:
  service_1:
    build: ./service_1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  service_2:
    build: ./service_2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      service_1:
        condition: service_healthy
      service_2:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge