version: '3.8'

services:
  service_1:
    build: ./service_1
    networks:
      - app-network

  service_2:
    build: ./service_2
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service_1
      - service_2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge